language: node_js
node_js: node
deploy:  radiant-woodland-47931
  provider: heroku
  api_key:
    secure: 3SI+ZnjP41hjldhBy/8kCtdscKLa0G8H74ypQqwksJDWX52xn8ZrwYovP8qDuAE7nktPhGAbSDs6mcmG7bg0qNY8qpbEZ/L8lQPl3bwRFkutR67gdnSkuFAXEoJ/BPikEHU4SraHY7NBF8aGpG96eVegfVUxLGpXPAjGRKqmY5Y4LVKtH1p4ylvLkrBZBZU7BEdXFc9ldEhAr3Fr3bZ0EjQ6pLpc9HQG3kSY+GLcTZQYioefHcAs5gicq4zkYxIbQUQM4f3z2zMpVfl45xI05wqn4xLWUHQqbJQHinqym/Xch2FXcjm9pbD/E61XJBRbh9ijCa0xsVSwpY3xRwBeosE7bslcCQwQE19pCnEe89N5J5lYPCXXgL+PrSY0qnJL9l8hI7NOGbFwzvDpFyyetp2FYbWoZnyQo0aGRv2qAdDM+5I0/9MfsZTebR0PdpquCwy/gdxEO4mkqywzl1Qo8AbjVSQJXa0ZB/Z3LgmYb8ItKOXU1pBaLvE9ebgTll6aWYlDMmVvWrEWJsG0cPqnSvg1aItoNJkLyeG8kXPQIVX3qu00Tpgig1n8ep7jpvnUPeX4GaOkPFWVXczXH1/loFMKLOMDikFcRicnmeHFJQ9g5RHFU1rIBcZO1J8rU5UPR5GiymblXR3Vru7OJgfPnBB76R+bt7bKI71KOFErII8=
  app: node-shopping-list-integration-tests
  on:
    repo: mcbanks76/node-shopping-list-integration-tests
